version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: We420?Z4!

  python_script:
    build: .
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: twitter_v2
      DB_USER: Admin
      DB_PASSWORD: We420?Z4!

volumes:
  mongodb_data:
