version: '3.8'

services:
  mongodb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5
  other_service:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy

  metric_system:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: twitter_v2
      DB_USER: Admin
      DB_PASSWORD: your_password_here # Make sure this matches MONGO_INITDB_ROOT_PASSWORD
    networks:
      - metric-network

networks:
  metric-network:
    name: metric-network

volumes:
  mongo-data: