version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: your_password_here
    volumes:
      - mongo-data:/data/db
    networks:
      - metric-network

  metric_system:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: twitter_v2
      DB_USER: Admin
      DB_PASSWORD: your_password_here # Make sure this matches MONGO_INITDB_ROOT_PASSWORD
    networks:
      - metric-network

networks:
  metric-network:
    name: metric-network

volumes:
  mongo-data: