version: '3.8'

services:
  metric_system:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: twitter_v2
      DB_USER: Admin
      DB_PASSWORD: ***REMOVED***
    networks:
      - metric-network

networks:
  metric-network:
    external: true